import argparse
import os
import h5py
import pandas as pd
import tqdm

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--folder", type=str, help="Folder containing the segemntation files generated by TotalSegmentator")
    args = parser.parse_args()
    folder = args.folder

    patient_id_table = pd.read_csv("data/train_series_meta.csv", index_col=1)

    for file in tqdm.tqdm(os.listdir(folder)):
        series_id = file[:-4]
        file_path = os.path.join(folder, file)
        with h5py.File(file_path, "r") as f:
            segmentation_labels = f["segmentation_labels"][()]

        patient_id = patient_id_table.loc[int(series_id), "patient_id"]
        with h5py.File(os.path.join("data_hdf5", str(patient_id), series_id, "ct_3D_image.hdf5"), "r") as f:
            ct_3D_image = f["ct_3D_image"][()]

        assert segmentation_labels.shape[2] == ct_3D_image.shape[0], "Segmentation and image have different depths. Shape: {} {}".format(segmentation_labels.shape, ct_3D_image.shape)
        assert segmentation_labels.shape[0] == ct_3D_image.shape[2], "Segmentation and image have different heights. Shape: {} {}".format(segmentation_labels.shape, ct_3D_image.shape)
        assert segmentation_labels.shape[1] == ct_3D_image.shape[1], "Segmentation and image have different widths. Shape: {} {}".format(segmentation_labels.shape, ct_3D_image.shape)
